version: '3.8'
services:
  amazon-cart:
    container_name: amazon-cart
    image: amazon/cart:1.0.0-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: /jwt/publicKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt
  amazon-jwt:
    container_name: amazon-jwt
    image: amazon/jwt:1.0.0-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /jwt/privateKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt